name: RealiteClasses
version: 0.1.0
main: ru.realite.classes.RealiteClassesPlugin
api-version: "1.20"

commands:
  class:
    description: "Классы персонажей"
    usage: "/class [choose/change]"
    aliases: [classes]

permissions:
  realiteclass.choose:
    default: true
  realiteclass.change:
    default: false
  realiteclass.admin.set:
    default: op
